# Makefile for assignment 1 section 3
# Making hello.c

all:
#	arm-linux-gnueabihf-gcc -Wall -g -std=c99 -D _POSIX_C_SOURCE=200809L -Werror hello.c -o hello
	arm-linux-gnueabihf-gcc -Wall -g -std=c99 -D _POSIX_C_SOURCE=200809L hello.c -o hello
	cp hello $(HOME)/cmpt433/public/myApps/
